trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
variables:
  Packaging.EnableSBOMSigning: true

jobs:
- job: Job_1
  displayName: CELA job
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - task: ComponentGovernanceComponentDetection@0
  - task: notice@0
    displayName: NOTICE File Generator

- job: Job_2
  displayName: Build job
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - script: yarn install
    displayName: 'Yarn install'
  # DotNet Core needed for ESRP and building proxy
  - task: UseDotNet@2
    inputs:
      version: '2.x'
      performMultiLevelLookup: true

  # Use for linux: xvfb-run -a yarn run test
  # For some reason, azuredatastudio for linux does not execute the tests.
  - script: yarn run test
    displayName: 'Run unit tests'
  - script: yarn run publish
    displayName: 'Yarn publish'
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    inputs:
      ConnectedServiceName: 'ESRP Official Codesigning'
      FolderPath: '$(Build.SourcesDirectory)'
      Pattern: '*.vsix'
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "keyCode": "CP-233016",
            "operationSetCode": "OpcSign",
            "parameters": [
              {
                "parameterName": "FileDigest",
                "parameterValue": "/fd \"SHA256\""
              }
            ],
            "toolName": "sign",
            "toolVersion": "1.0"
          },
          {
            "keyCode": "CP-233016",
            "operationSetCode": "OpcVerify",
            "parameters": [],
            "toolName": "sign",
            "toolVersion": "1.0"
          }
        ]
      SessionTimeout: 120
    displayName: 'Signing extension'
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'SBOM'
    inputs:
      BuildDropPath: '$(Build.SourcesDirectory)'
  - task: CopyFiles@2
    inputs:
      contents: '*.vsix'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
