# Component Detection
name: "Component Detection"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  component-detection:
    runs-on: windows-latest
    name: "Component Detection"
    steps:
      - name: Download nugget
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
          location: 'C:\Windows'
      - uses: actions/checkout@v2
      - name: Connect to Nuget feed
        run: nuget.exe sources add -name ComponentGovernance  -source https://pkgs.dev.azure.com/1esSharedAssets/_packaging/ComponentGovernance/nuget/v3/index.json -password ${{ secrets.TEST_SECRET }} -username languye
      - name: Install Component Detection
        # run: nuget.exe install Microsoft.VisualStudio.Services.Governance.ComponentDetection -ConfigFile ${{ github.workspace }}/nuget.config
        run: nuget.exe install Microsoft.VisualStudio.Services.Governance.ComponentDetection

