# Component Detection
name: "Component Detection"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  component-detection:
    runs-on: ubuntu-latest
    name: "Component Detection"
    env:
      AZURE_DEVOPS_PAT: ${{ secrets.ADO_READER_PAT }}
    steps:
      - uses: nuget/setup-nuget@v1
      - run: nuget sources add -Name "ComponentGovernance" -Source "https://pkgs.dev.azure.com/1esSharedAssets/_packaging/ComponentGovernance/nuget/v3/index.json" -UserName "GitHub" -Password "$AZURE_DEVOPS_PAT"
      - name: Install Component Detection
        run: nuget install Microsoft.VisualStudio.Services.Governance.ComponentDetection
      - name: Execution scan
        run: find . -name *Loader
